api_version = "2025-01"

[[extensions]]
name = "RoundUp Donation"
handle = "roundup-donation-checkout"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/index.jsx"
target = "purchase.checkout.block.render"
