name = "RoundUp for Charity"
client_id = "78ee946529e7879acd99bd2d1709f913"
application_url = "https://66640ec9-c052-40ad-987a-ebb01cd9599c-00-2ixszdsr6rj46.picard.replit.dev"
embedded = true

[auth]
redirect_urls = ["https://66640ec9-c052-40ad-987a-ebb01cd9599c-00-2ixszdsr6rj46.picard.replit.dev/api/auth/callback"]

[webhooks]
api_version = "2025-01"

[access_scopes]
scopes = "read_products,write_products"
