name = "RoundUp for Charity"
client_id = "78ee946529e7879acd99bd2d1709f913"
application_url = "https://f0caf125-4acc-44bc-a183-0a471a2adf26-00-2o6cblxrhpv94.picard.replit.dev"
embedded = true

[auth]
redirect_urls = ["https://f0caf125-4acc-44bc-a183-0a471a2adf26-00-2o6cblxrhpv94.picard.replit.dev/api/auth/callback"]

[webhooks]
api_version = "2025-01"

[access_scopes]
scopes = "read_products,write_products"
