name = "RoundUp for Charity"
client_id = "78ee946529e7879acd99bd2d1709f913"
application_url = "https://e6b1e8bd-a711-487b-9f82-c05f47c13416-00-2uozzrnmcaep7.picard.replit.dev"
embedded = true

[auth]
redirect_urls = ["https://e6b1e8bd-a711-487b-9f82-c05f47c13416-00-2uozzrnmcaep7.picard.replit.dev/api/auth/callback"]

[webhooks]
api_version = "2025-01"

[access_scopes]
scopes = "read_products,write_products"
