name = "RoundUp for Charity"
client_id = "78ee946529e7879acd99bd2d1709f913"
application_url = "https://7bdc6d7d-5f8a-4a9b-895d-2ac77276fbc9-00-3glorqpf5rgbk.picard.replit.dev"
embedded = true

[auth]
redirect_urls = ["https://7bdc6d7d-5f8a-4a9b-895d-2ac77276fbc9-00-3glorqpf5rgbk.picard.replit.dev/api/auth/callback"]

[webhooks]
api_version = "2025-01"

[access_scopes]
scopes = "read_products,write_products"
