name = "RoundUp for Charity"
client_id = "78ee946529e7879acd99bd2d1709f913"
application_url = "https://91027c41-17a6-4b6a-aee6-833f5c3ab87b-00-hk4209lwvmsk.picard.replit.dev"
embedded = true

[auth]
redirect_urls = ["https://91027c41-17a6-4b6a-aee6-833f5c3ab87b-00-hk4209lwvmsk.picard.replit.dev/api/auth/callback"]

[webhooks]
api_version = "2025-01"

[access_scopes]
scopes = "read_products,write_products"
