name = "RoundUp for Charity"
client_id = "78ee946529e7879acd99bd2d1709f913"
application_url = "https://650a7c01-767c-4a9a-8646-81d13c2fc55d-00-39jk4i4olinqb.picard.replit.dev"
embedded = true

[auth]
redirect_urls = ["https://650a7c01-767c-4a9a-8646-81d13c2fc55d-00-39jk4i4olinqb.picard.replit.dev/api/auth/callback"]

[webhooks]
api_version = "2025-01"

[access_scopes]
scopes = "read_products,write_products"
