name = "RoundUp for Charity"
client_id = "78ee946529e7879acd99bd2d1709f913"
application_url = "https://cec24713-d66d-4197-915f-51947abeb0f0-00-3kazosz35b1nk.picard.replit.dev"
embedded = true

[auth]
redirect_urls = ["https://cec24713-d66d-4197-915f-51947abeb0f0-00-3kazosz35b1nk.picard.replit.dev/api/auth/callback"]

[webhooks]
api_version = "2025-01"

[access_scopes]
scopes = "read_products,write_products"
