name = "RoundUp for Charity"
client_id = "78ee946529e7879acd99bd2d1709f913"
application_url = "https://cf3a971d-9f61-433a-8e5a-80c975d7c834-00-1p2148jznta0l.picard.replit.dev"
embedded = true

[auth]
redirect_urls = ["https://cf3a971d-9f61-433a-8e5a-80c975d7c834-00-1p2148jznta0l.picard.replit.dev/api/auth/callback"]

[webhooks]
api_version = "2025-01"

[access_scopes]
scopes = "read_products,write_products"
