name = "RoundUp for Charity"
client_id = "78ee946529e7879acd99bd2d1709f913"
application_url = "https://ef06b77e-5fc7-4fb9-ad3e-75874815b0d7-00-qcrxypslt259.picard.replit.dev"
embedded = true

[auth]
redirect_urls = ["https://ef06b77e-5fc7-4fb9-ad3e-75874815b0d7-00-qcrxypslt259.picard.replit.dev/api/auth/callback"]

[webhooks]
api_version = "2025-01"

[access_scopes]
scopes = "read_products,write_products"
