name = "RoundUp for Charity"
client_id = "78ee946529e7879acd99bd2d1709f913"
application_url = "https://e254dec1-aed7-41f8-b39f-66e817c86197-00-gylebt30kx15.picard.replit.dev"
embedded = true

[auth]
redirect_urls = ["https://e254dec1-aed7-41f8-b39f-66e817c86197-00-gylebt30kx15.picard.replit.dev/api/auth/callback"]

[webhooks]
api_version = "2025-01"

[access_scopes]
scopes = "read_products,write_products"
