api_version = "2025-07"

[[extensions]]
name = "RoundUp POS Donation"
handle = "roundup-donation-pos"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/index.jsx"
target = "pos.purchase.post.action.render"
